class VueGenerator:

    def generate(self, layout_nodes):

        template = []
        template.append("<template>")
        template.append("  <div class='root'>")

        for node in layout_nodes:
            template.append(self._render_node(node, 2))

        template.append("  </div>")
        template.append("</template>\n")

        script = """
<script setup>
// Auto-generated by Vision2Code
</script>
"""

        style = """
<style scoped>
.root {
  padding: 20px;
}

.box {
  border: 1px solid #333;
  margin: 6px;
  min-height: 40px;
}

.row {
  display: flex;
  flex-direction: row;
}

.column {
  display: flex;
  flex-direction: column;
}
</style>
"""

        return "\n".join(template) + script + style


    def _render_node(self, node, depth):
        indent = "  " * depth

        if node.direction == "row":
            cls = "box row"
        elif node.direction == "column":
            cls = "box column"
        else:
            cls = "box"

        html = f"{indent}<div class='{cls}'>\n"

        for child in node.children:
            html += self._render_node(child, depth + 1)

        html += f"{indent}</div>\n"

        return html